<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>wang.bigbird.domain</groupId>
        <artifactId>bigbird-framework-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../bigbird-framework-parent/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>bigbird-framework-document</artifactId>
    <packaging>pom</packaging>
    <name>Bigbird Framework :: Document</name>
    <description>鸟域开发框架 :: 文档构件</description>

    <modules>
        <module>bigbird-framework-document-api</module>
        <module>bigbird-framework-document-excel</module>
        <module>bigbird-framework-document-pdf</module>
        <module>bigbird-framework-document-ppt</module>
        <module>bigbird-framework-document-word</module>
        <module>bigbird-framework-document-html</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>bigbird-framework-core</artifactId>
        </dependency>
    </dependencies>

</project>
