<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>wang.bigbird.domain</groupId>
        <artifactId>bigbird-framework-plugin</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>bigbird-framework-maven-plugin</artifactId>
    <packaging>pom</packaging>
    <name>Bigbird Framework :: Plugin :: Maven</name>
    <description>鸟域开发框架 :: 自定义插件 :: Maven</description>

    <modules>
        <module>bigbird-framework-mybatisplus-generator-maven-plugin</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <version>3.5</version>
        </dependency>
    </dependencies>

</project>
