<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>wang.bigbird.domain</groupId>
        <artifactId>bigbird-framework-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../bigbird-framework-parent/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>bigbird-framework-server</artifactId>
    <packaging>pom</packaging>
    <name>Bigbird Framework :: Server</name>
    <description>鸟域开发框架 :: Server构件</description>

    <modules>
        <module>bigbird-framework-server-core</module>
        <module>bigbird-framework-server-web</module>
        <module>bigbird-framework-server-rpc</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>bigbird-framework-core</artifactId>
        </dependency>
    </dependencies>

</project>
